language: php

php:
  - 5.4
  - 5.6
  - 7.0

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update && composer install --no-interaction
  - cd tests

script: phpunit -v