language: php
dist: precise
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update && composer install --no-interaction
  - cd tests

script: phpunit --stderr --debug
after_script:
  - cd ../
  - pwd
